.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/config.yml

Only updating the config.yml and bug_report.yml to point to the Redot-Engine repos instead of the Godot repos

Update ISSUE__TEMPLATES to point to Redot-Engine repo instead of Godot repo

---

platform/web/SCsub
platform/web/eslint.config.cjs
platform/web/js/engine/config.js
platform/web/js/engine/engine.externs.js
platform/web/js/engine/engine.js

The error this fixes can be reproduced by setting up export templates then clicking 
here's my GMTK 2024 game running on a web export for REDOT

fix: uses the exposed Redot global instead of the no longer existing Godot

---

misc/scripts/install_vulkan_sdk_macos.sh

Latest version of [SDK](https://vulkan.lunarg.com/sdk/home#mac) switched from DMG to ZIP.

[macOS] Update Vulkan SDK install script.

---

editor/export/export_template_manager.cpp

Points it to a redotengine URL.  Probably want to change depending on how our infrastructure is laid out following release.
I mainly wanted to raise awareness that this needs to be altered, preferably before a release (even if it points to a repo where there are no export templates available, just as long as it's not upstream servers).

Change export template repo mirror URL

---

editor/editor_about.cpp

Branding change.  This is unrelated to the COPYRIGHT.txt which feeds the lists below it.

Branding change on About->Third-party Licenses widget

---

doc/classes/ProjectSettings.xml
editor/plugins/node_3d_editor_plugin.cpp
editor/plugins/node_3d_editor_plugin.h
main/main.cpp

Changed the default color of the preview enviroment and the default clear color to the same, also added a button to the preview so you can choose horizon color.
old
new

Changed color of the preview enviroment and added hz button

---

misc/dist/html/editor.html
misc/dist/html/full-size.html

User viewable messages altered to replace branding.  Some URLs error messages point to will need to be changed in the future when redot-docs is publicly available and hosted via URL, but that can wait.

User viewable msgs changed for rebrand on HTML export dists

---

platform/linuxbsd/freedesktop_screensaver.cpp
platform/linuxbsd/os_linuxbsd.cpp
platform/linuxbsd/x11/display_server_x11.cpp

This changes the name of the window on Linux(X11) to Redot. Looks like you are merging everything into the branch redot-merge-code. Hopefully this is the correct branch.

Updated window branding on Linux.

---

editor/export/export_template_manager.cpp
platform/web/export/export_plugin.cpp
platform/windows/display_server_windows.cpp
platform/windows/export/export_plugin.cpp

- Rebrand scheduled task for runnable deploy ssh option
- Export template manager string update
- web export proj name altered if no proj name set
- string change in display_server_windows.cpp
Just a few string replacements and an update to the remote SSH options that changed the scheduled task name on the remote Windows target device

Various editor strings (rebranding)

---

editor/themes/editor_theme_manager.cpp

This update changes the "Light" theme in the editor to use red rather than blue for its primary accent color to stay "on-brand."
The desired effect of this change is that users who prefer light themes over dark themes will still have an experience that feels like Redot rather than Godot, so that Redot can have its trademark dark mode theme and an accompanying light mode.

Use "Redot Red" for accent color in Light theme.

---

COPYRIGHT.txt
REDOT_AUTHORS.md
core/SCsub
core/config/engine.cpp
core/config/engine.h
core/core_bind.cpp
core/core_bind.h
core/core_builders.py
core/version.h
doc/classes/Engine.xml
editor/editor_about.cpp
methods.py
version.py

Fix author info referring to Godot authors, now refers to REDOT_AUTHORS.md
Fix donor info referring to Godot donors, now empty
Correct COPYRIGHT.txt to properly refer to reflect Redot rebrand
Add Godot author info
Add Godot version compatibility info
Add Godot donor info

Fix Project Manager listing incorrect info

---

modules/websocket/packet_buffer.h
modules/websocket/wsl_peer.cpp
modules/websocket/wsl_peer.h

Allows WSLPeer to grab the length of incoming messages
(cherry picked from commit godotengine/godot@e11d58189e1cc161e76cfb816c3eebda66f917ff)

[4.3] Fix websocket dropping messages for WSLPeer

---

editor/plugins/asset_library_editor_plugin.cpp

(cherry picked from commit 5f0300f86346aef1eece10d15c1f64059b9b9965)

[4.3] Remove `(Official)` from asset library button

---

CONTRIBUTING.md

PR Guidelines added
Pre-Commit link added
Updated old Godot doc links to the new Redot website doc links
Changed links to the Discord for contribution info to more appropriate ones now that the Proposals repo is ready to go

[4.4] Updated CONTRIBUTING.md w/ PR Guideline and Redot Docs links

---

.github/workflows/linux_builds.yml
.github/workflows/windows_builds.yml

These have a tendency to consume a more notable amount of GH Action resources by their mere existence so they are being removed to free up time, GHA run slots, and cache for future workflow runs.

Remove CI jobs that do not match Godot

---

drivers/gles3/shaders/canvas.glsl
servers/rendering/renderer_rd/shaders/canvas.glsl

Cherry-picked from godotengine/godot#97260
Supersedes #744
This ensures that you are actually snapping to pixels in the viewport and not an arbitrary amount
(cherry picked from commit godotengine/godot@e75900e1ad1a2c699829335ad3be27b4e01afec1)

[4.3] Calculate pixel snap in canvas space instead of world space

---

core/math/a_star_grid_2d.cpp
core/math/a_star_grid_2d.h
doc/classes/AStarGrid2D.xml

Rework of the previous PR for AStarGrid2D to limit the amount of maximum traversals per pathing request. Generally useful when dealing with very large maps where we don't want to search the entire world.
Releated PR: https://github.com/godotengine/godot/pull/85036
supersedes #741

[4.3] feat: add maximum traversals to astargrid2d

---

COPYRIGHT.txt
LOGO_LICENSE.txt

Updated logo copyright info in COPYRIGHT.txt
Updated LOGO_LICENSE.txt to reflect current copyright info

[4.3] logo license and copyright

---

COPYRIGHT.txt

The creator of the logos and icons had 2 sections in COPYRIGHT.txt they have been condensed into one

[4.3] Condense two copyright sections by same author into one

---

core/math/a_star_grid_2d.cpp
core/math/a_star_grid_2d.h
doc/classes/AStarGrid2D.xml

Rework of the previous PR for AStarGrid2D to limit the amount of maximum traversals per pathing request. Generally useful when dealing with very large maps where we don't want to search the entire world.
Related PR: https://github.com/godotengine/godot/pull/85036
cherry-picked from #750

Add maximum traversals to AStarGrid2D

---

COPYRIGHT.txt
LOGO_LICENSE.txt

Updated logo copyright info in COPYRIGHT.txt
Updated LOGO_LICENSE.txt to reflect current copyright info
supersedes #737

Update logo license and copyright file

---

methods.py
misc/msvs/props.template
misc/msvs/vcxproj.template

Supersedes #664
Fixed the created visual studio project created by scons was not able to debug by default, as it was asking for godot executable
changed the configuration from Godot to Redot

Fixed the visual studio project creation for debugging

---

core/math/projection.cpp
tests/core/math/test_projection.h
tests/test_main.cpp

Relates to godotengine/godot#68878, specially when using orthographic projection.
Also adds some tests.
Adapted from godotengine/godot#95303
(cherry picked from commit 07730283d334280e2b4e2bede4902a796eabb4c2)

[4.3] Fix `Projection::invert` on orthogonal projections and others.

---

platform/macos/export/export_plugin.cpp

(cherry picked from commit 09fae16ef69b9b380e119431f224dd8ebc7dce99)

[4.3] Rebrand macos exports to Redot

---

modules/mono/build_scripts/build_assemblies.py
modules/mono/editor/Godot.NET.Sdk/Godot.NET.Sdk/Godot.NET.Sdk.csproj
modules/mono/editor/Godot.NET.Sdk/Godot.SourceGenerators/Godot.SourceGenerators.csproj
modules/mono/editor/GodotTools/GodotTools.IdeMessaging/GodotTools.IdeMessaging.csproj
modules/mono/glue/GodotSharp/GodotSharp/GodotSharp.csproj
modules/mono/glue/GodotSharp/GodotSharpEditor/GodotSharpEditor.csproj

Rebrand dotnet project metadata to reference Redot
Will need correction when https://www.nuget.org/packages/Redot.NET.Sdk is made.

[4.3] Fix mono SDK references temporarily

---

editor/engine_update_label.cpp

Fixes #792 
Fix `EngineUpdateLabel` status version trimming

[4.3] Fix `EngineUpdateLabel` referring to godotengine.org

---

doc/classes/ColorPicker.xml
scene/gui/color_picker.cpp

Expose `ColorPicker.display_old_color` as a property

Expose `ColorPicker.old_color` as a property

---

scene/gui/color_mode.h

It seems to be vestigial inherited from the ColorPicker refactor

[4.3] Remove `ColorModeOKHSL.get_shape_override`

---

scene/gui/color_picker.cpp

Remove vbl child from `ColorPicker`
Remove vbr child from `ColorPicker`, prefer `real_vbox`

[4.3] Remove superfluous `ColorPicker` Containers

---

scene/gui/color_picker.cpp

[4.3] Fix `ColorPicker` overbright indicator position

---

scene/gui/color_picker.cpp

[4.3] Remove hide on `ColorPicker` color picking

---

core/math/projection.cpp
tests/core/math/test_projection.h
tests/test_main.cpp

Relates to godotengine/godot#68878, specially when using orthographic projection.
Also adds some tests.
Adapted from godotengine/godot#95303

Fix `Projection::invert` on orthogonal projections and others.

---

scene/gui/color_mode.h
scene/gui/color_picker.cpp

[4.3] Enable `ColorPicker` RGB+RAW modes to have overbright values

---

editor/gui/editor_spin_slider.cpp

(cherry picked from commit blazium-engine/blazium@a501d9f81282ad6030f5395fc86e8c15ded7116b)

[4.3] Fix `EditorSpinSlider` grabber doesn't follow parent when scrolling

---

editor/plugins/canvas_item_editor_plugin.cpp

(cherry picked from commit blazium-engine/blazium@5ca9caa0f88c7ee4c9cad38decf0a064eb126bab)

[4.3] Fix `CanvasItemEditor` redraw on key echo

---

editor/plugins/canvas_item_editor_plugin.cpp
editor/plugins/canvas_item_editor_plugin.h

(cherry picked from commit blazium-engine/blazium@5ca9caa0f88c7ee4c9cad38decf0a064eb126bab)

[4.3] Unify `CanvasItemEditor` duplicate hovering behavior

---

editor/plugins/canvas_item_editor_plugin.cpp
editor/plugins/canvas_item_editor_plugin.h

(cherry picked from commit blazium-engine/blazium@5ca9caa0f88c7ee4c9cad38decf0a064eb126bab)

[4.3] Overhaul `CanvasItemEditor` snap lines drawing and input

---

doc/classes/ColorPicker.xml
editor/icons/WheelPickerCursor.svg
editor/themes/editor_theme_manager.cpp
scene/gui/color_picker.cpp
scene/gui/color_picker.h
scene/theme/default_theme.cpp
scene/theme/icons/color_picker_wheel_cursor.svg

Replaces `ColorPicker`'s HSV wheel hue indicator with `wheel_picker_icon` texture which by default is the same as `picker_cursor`
https://github.com/user-attachments/assets/29cbf998-2e7e-4374-ab98-342c2c6b56b6

Add `wheel_picker_cursor` theme icon to `ColorPicker`

---

core/extension/extension_api_dump.cpp

(cherry picked from commit 5fb6d30604b392776265052c621eef0470d8fadb)

[4.3] Fix `GDExtensionAPIDump` lacking status_version header

---

editor/engine_update_label.cpp

This fix de-references godotengine from the update URL.

[4.3] Fix Godot Reference for update URL

---

editor/icons/Snap.svg

Icon bug introduced in #726
The snap icon in the editor will error our without `Snap.svg`

Fix Snap icon removal introduced in e8e8a88

---

doc/classes/ColorPicker.xml
scene/gui/color_picker.cpp

Improved centering of the `ColorPicker.wheel_picker_cursor` icon
The imperfect nature of perfecting the centering may also be down to the instability of the pixels caused by float truncation.

Add rotation to the `ColorPicker.wheel_picker_cursor` icon

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/PULL_REQUEST_TEMPLATE.md

Fixing godot reference in the issue & pr template
leaving the .godot project folder because currently we are still using it for compatibility reasons.

Fix godot references in the issue & PR template

---

editor/engine_update_label.cpp
editor/engine_update_label.h

[4.3] Replace `versions.json` check with Github release check

---

doc/classes/Node.xml

`Node._unhandled_picking_input` works for any InputEvent, not just InputEventKey.

[4.3] Correct `Node._unhandled_picking_input` to refer to InputEvent

---

core/string/ustring.cpp

Performs a single allocation, only when any instances are found, and avoids concatenations and other unnecessary conversions.
(cherry picked from commit cbaec62b0335bc70c7cf7d55651678591bafafd2)
---
From godotengine/godot#92546
Fixes #861
This is being cherry-picked from godotengine/godot#92546 in order to solve a bug with `String::replace` which triggers #861 when `String::split_float` is called because godotengine/godot#95613 changed `String::split_float` to expect a null terminator which `String::replace` does not provide on empty returns, (which appears to be a bug) godotengine/godot#97082 had cherry-picked godotengine/godot#92546 without godotengine/godot#95613 or otherwise fixing `String::replace`'s behavior to produce a null terminator character on empty strings. Since it fixes a …

[4.3] Optimize `String::replace` methods

---

platform/windows/os_windows.cpp

Causes godotengine/godot#99108 conversion errors on 32-bit Windows because size_t on 32-bit is unsigned int whereas on 32-bit Windows' SIZE_T is unsigned long. This is how it was solved for godotengine/godot#99107 with godotengine/godot#99280.

[4.3] Fix 32-bit Windows build

---

doc/classes/Object.xml
doc/classes/SceneTree.xml

Fixes issues with sphinx documentation crashing if it leaves the classes "unmigrated".

[4.3] Fix invalid doc references to godot_notifications

---

misc/dist/linux/redot.6

I don't know how I missed this, but right now accessing man page requires `man godot` rather than `man redot` -- This solves that.

[4.3] Corrected manpage

---

doc/classes/EditorInterface.xml
editor/editor_interface.cpp
editor/editor_interface.h

See godotengine/godot-proposals#10895
Closes #907
(cherry picked from commit godotengine/godot@5d72926100beb3a23a889b3c9a084d2ec2b9ae7e)
---
Original `get_open_scenes` function provided by Godot is quite limited as it only returns a string array containing the names of opened scenes. This feature is necessary for situations where accessing all opened scenes in depth is required and it is also essential for the Jenova Framework Hot-Reloading feature.
This commit includes :
* Changes to the Editor Interface API (`editor_interface.h` and `editor_interface.cpp`)
* Updates to the Editor Interface documentation (`EditorInterface.xml`)

[4.3] Added get_open_scenes_roots to Editor Interface API

---

modules/dds/texture_loader_dds.cpp

Original PR: godotengine/godot#99600
(cherry picked from commit e297506365559f2b13534b9dd5f3250db06975a5)

[4.3] Round DDS width/height to next divisor multiple for block compression

---

core/math/math_funcs.h
core/variant/variant_utility.cpp
core/variant/variant_utility.h
doc/classes/@GlobalScope.xml
tests/core/math/test_math_funcs.h

Closes Redot-Engine/redot-proposals#12

Add sigmoid(), sigmoid_approx(), sigmoid_affine() and sigmoid_affine_approx() functions

---

.github/workflows/static_checks.yml

Original PR: godotengine/godot#101363
(cherry picked from commit 829ad307f8c06134229256d0fc564fabd4e8826b)
---
Works around [awalsh128/cache-apt-pkgs-action#141](https://github.com/awalsh128/cache-apt-pkgs-action/issues/141), this shouldn't add too much to the build iteration time as it's a single package (it used to be several when we added this back then).

[4.3] CI: Install apt dependencies directly, works around issue with `awalsh128/cache-apt-pkgs-action`

---

editor/themes/editor_theme_manager.cpp

We want to change the color scheme to something more subtle the red has long received a lot of hate.  
Initially we wanted to switch to the [godot-minimal-theme ](https://github.com/passivestar/godot-minimal-theme) but that turned out more complicated than not as it has a 700 line GDScript file that changes a lot of nuances like spacing and margin.   
So we decided we could just use the color values from it for now.   Feel free to review my values but i belive they are correct.

Change the default theme to dark scheme from minimal-theme

---

core/object/object.h
doc/classes/@GlobalScope.xml
doc/classes/Node.xml
doc/classes/TreeItem.xml
drivers/gles3/rasterizer_canvas_gles3.cpp
drivers/gles3/rasterizer_canvas_gles3.h
drivers/gles3/shaders/canvas.glsl
drivers/gles3/shaders/sky.glsl
editor/connections_dialog.cpp
editor/gui/scene_tree_editor.cpp
editor/gui/scene_tree_editor.h
editor/reparent_dialog.cpp
editor/scene_tree_dock.cpp
editor/scene_tree_dock.h
scene/gui/tree.cpp
scene/gui/tree.h
scene/main/node.cpp
scene/main/node.h
scene/resources/3d/primitive_meshes.cpp
scene/resources/mesh.cpp

- Depends on #933
Performance PRs:
- godotengine/godot#87558
- godotengine/godot#99498
- godotengine/godot#99700
Extra PRs:
- godotengine/godot#96124
- godotengine/godot#97722
- godotengine/godot#98745

[4.3] Cherry-picks for the 4.3 (4.3.1) branch - 1st performance batch

---

core/extension/gdextension.cpp
core/io/stream_peer.cpp
doc/classes/AudioStream.xml
editor/export/export_template_manager.cpp
editor/script_create_dialog.cpp
scene/resources/compositor.cpp
scene/resources/compositor.h
servers/audio/audio_stream.cpp

GDExtension Bug PRs:
- godotengine/godot#98914
- godotengine/godot#99403
- godotengine/godot#99981
- godotengine/godot#100126
- godotengine/godot#100318
Extra PRs:
- godotengine/godot#96616

[4.3] Cherry-picks for the 4.3 (4.3.1) branch - 1st gdextension bugs batch

---

modules/gdscript/config.py
modules/gdscript/doc_classes/GDScriptSyntaxHighlighter.xml
modules/gdscript/register_types.cpp

- Original PR godotengine/godot#95764
(cherry picked from commit 3fe644de86b6a9fa96bbbbaa7746c52005848d96)
---
- Related godotengine/godot-proposals#10374
|Before | After |
| --- | --- |
| ![before](https://github.com/user-attachments/assets/96cfb154-2bc0-419b-8465-63c31aebaa60) | ![after](https://github.com/user-attachments/assets/97a9fc39-82ff-4da0-969a-144126ec830b) |

[4.3] Expose GDScript syntax highlighter to editor plugins

---

editor/editor_file_system.cpp
editor/editor_file_system.h
editor/editor_log.cpp
editor/editor_node.cpp
modules/gltf/editor/editor_scene_importer_blend.cpp
scene/2d/tile_map.cpp
scene/gui/rich_text_label.cpp
scene/gui/rich_text_label.h

Fix issue with Tilemaps not displaying correctly since redot-4.3.1-alpha.1
- Revert "Rationalize busy waits" (3f4c085593ba6e286db01613f789a8c833e81ec8) from #933
```git revert -m 1 3f4c085593ba6e286db01613f789a8c833e81ec8```
- Cherry -pick "[Fix setting TileMap data compatibility format broken by #98898](https://github.com/Redot-Engine/redot-engine/pull/977/commits/e105e675b937a741c51506453e2639dec04fc4a6)" fix for 22c260477641fac79ef964f1bb5f4198e35d25da (#933)
```git cherry-pick -x 282425eefb9e97ab31ff0f25f3b135ed2e2aca42```

[4.3] Fix Tilemap release display bug

---

modules/raycast/raycast_occlusion_cull.cpp

- Original PR:  godotengine/godot#100060
- Fixes #972
(cherry picked from commit 329d25b1fafccf5e8059c494b6210f1805b0b4bb)
---
- Related godotengine/godot#100032
On subsequent calls to `_transform_vertices_range()` (where `p_from` would have been adjusted) it would still start writing to the same index in of `xformed_vertices` effectively overwriting and corrupting vertex data previously written.
The correct implementation is to offset `p_write` with 3*`p_from`.
I tested using [occlusion_culling_mesh_lod](https://github.com/godotengine/godot-demo-projects/tree/master/3d/occlusion_culling_mesh_lod) for both double and float builds.
Before:
After:

[4.3] Fixed occlusion culling buffer getting overwritten in larger scenes

---

.github/workflows/redot_cpp_test.yml
.github/workflows/runner.yml

- 4.3 version of #982
Ensures that we are testing [redot-cpp](https://github.com/Redot-Engine/redot-cpp) alongside godot-cpp in our CI, this ensures we'll actually address issues related to redot-cpp when we merge PRs.

[4.3] CI: Add redot-cpp testing

---

.github/actions/redot-cpp-build/action.yml
.github/workflows/linux_builds.yml

- master version of #981
Ensures that we are testing [redot-cpp](https://github.com/Redot-Engine/redot-cpp) alongside godot-cpp in our CI, this ensures we'll actually address issues related to redot-cpp when we merge PRs.

CI: Add redot-cpp testing action

---

core/config/engine.cpp
core/extension/gdextension_interface.cpp
core/extension/gdextension_interface.h
core/version.h
doc/classes/Engine.xml

Add more godot compatible version macros
Add `build` to `Engine::get_godot_compatible_version_info`
Update `Engine.get_godot_compatible_version_info` documentation
Fix `Engine.get_version_info` documentation for `string`

[4.3] Add `get_redot_version` to GDExtension interface

---

core/config/engine.cpp
core/extension/gdextension_interface.cpp
core/extension/gdextension_interface.h
core/version.h
doc/classes/Engine.xml

- Original PR: #979
Add more godot compatible version macros
Add `build` to `Engine::get_godot_compatible_version_info`
Update `Engine.get_godot_compatible_version_info` documentation
Fix `Engine.get_version_info` documentation for `string`
(cherry picked from commit 2ccf5447ba499f3876aae39c366dbdc4a854990b)

Add `get_redot_version` to GDExtension interface

---

README.md

Added a new text block at the end of the readme file to link this repo to our experimental repo making it easier to navigate between the two from within GitHub

Added a section of text in readme to link to the  ReX repo

---

.github/actions/godot-deps/action.yml
.github/workflows/linux_builds.yml
SConstruct
methods.py
pyproject.toml

- Original PR: godotengine/godot#99134
(cherry picked from commit 66fe2c8b44f34ea72892fed9594396d33a59f251)
Fixes 4.3 CI build failures for linux editor builds with clang sanitizers.
---
* Supersedes godotengine/godot#85968
* Supersedes godotengine/godot#98907
As discussed in this RocketChat thread[^1], the bump to Ubuntu 22.04 for our GitHub Actions have raised the lower bounds of support for both Python and SCons. As our current minimum versions for both (3.1.2 for SCons & 3.6 for Python) are _well_ into EOL as-is, it feels ideal to bump the versions in tandem. In contrast to previous PRs trying to have other changes in tandem, this is _strictly_ focused on bumping the minimum versions
Immediate benefits include:
* Having a minimum Python version that matches the minimum supported …

[4.3] SCons: Bump minimum version of SCons to 4.0 & Python to 3.8

---

core/extension/extension_api_dump.cpp

To retain Godot GDExtension compatibility, relies on Godot's `header`, Redot's GDExtension header is in `redot_header`
- Related redot-cpp PR: Redot-Engine/redot-cpp#25

[4.3] Add godot compatibility header to GDExtension API dump

---

core/extension/extension_api_dump.cpp

- Original PR: #1001
To retain Godot GDExtension compatibility, relies on Godot's `header`, Redot's GDExtension header is in `redot_header`
(cherry picked from commit 96e7bce528c5b08905eacd528ff4d6ea411c8ffa)

Add godot compatibility header to GDExtension API dump

---

core/extension/extension_api_dump.cpp

To retain Godot GDExtension compatibility, relies on Godot's `header`, Redot's GDExtension header is in `redot_header`
(cherry picked from commit 96e7bce528c5b08905eacd528ff4d6ea411c8ffa)

[4.4] Add godot compatibility header to GDExtension API dump

---

.github/workflows/linux_builds.yml

- Original PR: godotengine/godot#105661
(cherry picked from commit 92b1b0402c1a35506649d208e3d25bd4a04fffaf)
---
Turns out we can just ditch the middleman entirely. Ubuntu-22.04's implementation of `mesa-vulkan-drivers` is already satisfactory for our tests, so installing that directly fixes all of our issues

[4.4] CI: Remove legacy dependency

---

.github/actions/redot-cpp-build/action.yml
.github/workflows/linux_builds.yml

- Cherry-picked from #1009
(cherry picked from commit 4eee6655318609595dbc453811e00fed676c1704)

Fix redot-cpp-build CI action

---

core/config/project_settings.cpp

- Relies on #1020 
This ensures that whenever a Redot project is made, opened, or converted from Godot and saved, Godot will warn if/when you try to bring it back to Godot.

Add Redot as a project feature to protect Redot projects

---

core/config/project_settings.cpp

- Original PR: #1023 
This ensures that whenever a Redot project is made, opened, or converted from Godot and saved, Godot will warn if/when you try to bring it back to Godot.
(cherry picked from commit 02abb1e8a19b715a1b210fa019a6d8dbe1fd140a)

[4.3] Add Redot as a project feature to protect Redot projects

---

core/config/project_settings.cpp

- Original PR: #1023 
This ensures that whenever a Redot project is made, opened, or converted from Godot and saved, Godot will warn if/when you try to bring it back to Godot.
(cherry picked from commit 02abb1e8a19b715a1b210fa019a6d8dbe1fd140a)

[4.4] Add Redot as a project feature to protect Redot projects

---

core/core_bind.cpp
core/debugger/debugger_marshalls.cpp
core/doc_data.h
core/extension/extension_api_dump.cpp
core/io/json.cpp
core/object/script_language_extension.h
core/object/undo_redo.cpp

- Based on #1029 
I did a test with a blank project. Before the changes
```
$ ps -p `pgrep redot` -o vsz,rss,pmem                                                                         
VSZ   RSS %MEM
4121136 791364  1.2
```
After the changes:
```
$ ps -p `pgrep redot` -o vsz,rss,pmem                                                                         
VSZ   RSS %MEM
2300024 689524  1.0
```
I think this is an unrealistic, but it was consistently less resource intensive for both the CPU and for the RAM after repeated tests.
We can do better with memory management and I think this is a good starting point. I meant to pull these changes in from ReX before, but I must have forgot to. That's not an intentional pun.

Preallocate vectors with known size

---

platform/android/java/lib/src/org/godotengine/godot/plugin/GodotPluginRegistry.java

Godot android platform support has a very specific way to search for plugins to be loaded: they must have a metatadata to name them with prefix "org.godotengine.plugin.v(1|2)".
Plugins coming form the Asset Library, and locally built plugins, are using this convention.
The recent change of using "org.redotengine.plugin.v(1|2)" as the prefix for plugins breaks all existing Android plugin codebase. This seems not to be the intention of Redot devs becuase:
1. Pre-existing plugins from the same source still work on other platform (i.e. Poing ADMOB plugin still works on iOS).
2. Redot claims to be backward compatible with Godot.
3. All breaking changes are currently confined to ReX.
This PR allows for naming the new modules with "redotengine", to possibly leverage future changes in the …

Fix android plugin prefix compatibility regression

---

misc/scripts/install_vulkan_sdk_macos.sh

Modified the Vulkan install script for Mac to target 1.4.313.1 instead of the latest, as this appears to be the last known version to work on Mac OS 10.3.

[4.4] Pin Vulkan SDK version to 1.4.313.1 for compatibility with Mac 10.3.

---

.github/workflows/changelog_builder.yml

Enables to automatically construct release changelog descriptions using [release-changelog-builder](https://github.com/marketplace/actions/release-changelog-builder). This streamlines the creation of release tags so as to list every notable change akin to what was already being done before.

Add release changelog builder

---

.github/workflows/changelog_builder.yml

- Original PR: #1058 
(cherry picked from commit 859644a8f78e50c9af2e5c81ad6c04d8da9f790b)
---
Enables to automatically construct release changelog descriptions using [release-changelog-builder](https://github.com/marketplace/actions/release-changelog-builder). This streamlines the creation of release tags so as to list every notable change akin to what was already being done before.

[4.4] Add release changelog builder

---

.github/workflows/changelog_builder.yml

The resolver's filter regex for 4.3 should be `redot-(4\\.3(?:\\.\\d+)?)-(?:(alpha|beta|rc)\\.(\\d+)|(stable))` and for 4.4 should be `redot-(4\\.4(?:\\.\\d+)?)-(?:(alpha|beta|rc)\\.(\\d+)|(stable))`

Fix changelog builder tag resolver and title transformers

---

core/extension/gdextension_library_loader.cpp

- Fixes #1071  
Add disable flag via `disable_godot_checks`

Add Godot drop-in replacement for GDExtension version checks

---

scene/main/window.cpp

- Fixes #1037 
- Closes #1086 
- Closes #1087 
Ensure that when a translated title is being applied to the main window it isn't empty. If it is break early to prevent setting `(DEBUG)` as the title.  Instead it will keep the title it had previously.  The Project Manager currently is the only instance making this check necessary.
Testing of the engine after the fix shows translations for window titles working as expected. Titles for current project running projects and popup dialogues are working as intended

Fix project manager title showing as (DEBUG) 
