- doc/classes/Animation.xml
- doc/classes/AnimationPlayer.xml
- editor/animation_track_editor.cpp
- editor/animation_track_editor.h
- editor/editor_node.cpp
- editor/icons/Marker.svg
- editor/icons/MarkerSelected.svg
- editor/plugins/animation_blend_tree_editor_plugin.cpp
- editor/plugins/animation_blend_tree_editor_plugin.h
- editor/plugins/animation_player_editor_plugin.cpp
- editor/plugins/animation_player_editor_plugin.h
- scene/animation/animation_blend_tree.cpp
- scene/animation/animation_mixer.cpp
- scene/animation/animation_mixer.h
- scene/animation/animation_player.cpp
- scene/animation/animation_player.h
- scene/resources/animation.cpp
- scene/resources/animation.h
See original PR
https://github.com/godotengine/godot/pull/91765
> Add markers to animation

- editor/themes/editor_theme_manager.cpp
> :zap: update theme

- core/io/http_client_tcp.cpp
Update the useragent string utilized by http_client_tcp.cpp to reflect the new project name.
> Update useragent to reflect new project name

- editor/editor_node.cpp
- platform/linuxbsd/x11/display_server_x11.cpp
- Fixes URLs in help submenu
- Fixes X11 window decorator hints on linuxbsd platform (rebranding only)
> Misc branding changes take 2

- .github/workflows/linux_builds.yml
- .github/workflows/windows_builds.yml
Added the Linux Editor build
Added the Windows Editor w/mono 
Created step for generating glue code
Created step for building GodotSharp
> Redot merge code fiix CI pipeline

- editor/editor_settings.cpp
- editor/themes/editor_theme_manager.cpp
I used this theme on my previous personal fork of upstream.  I'd like to add it as a non-default option to Redot in case anyone else wants to use it.
Not part of rebranding initaitive.  Ignore until after first release if needed.
> Add Indigo theme

- editor/themes/editor_theme_manager.cpp
proper base color added:
preset_base_color = Color(0.17, 0.17, 0.20);
"You dabbed on Bio so hard, you turned him into a cartoonist" - McDubh
Lo siento, mi amigos!
> base color correct from original merge

- core/SCsub
- core/config/project_settings.cpp
- core/core_bind.cpp
- core/crypto/SCsub
- core/input/godotcontrollerdb.txt
- core/io/compression.cpp
- core/io/file_access_pack.h
- core/io/json.cpp
- core/io/remote_filesystem_client.cpp
- core/math/convex_hull.cpp
- core/math/transform_interpolator.cpp
- core/object/class_db.h
- core/object/script_language.h
- core/os/safe_binary_mutex.h
- core/string/string_builder.cpp
- core/string/string_builder.h
- core/templates/hash_map.h
- core/templates/hash_set.h
- core/version.h
Core was surprisingly light. 
Two notes: If we want to change the file extension for whatever reason: `core/config/project_settings.cpp` is where to do it.
> Deref Godot: core/

- drivers/backtrace/SCsub
- drivers/coremidi/midi_driver_coremidi.cpp
- drivers/d3d12/SCsub
- drivers/d3d12/rendering_device_driver_d3d12.cpp
- drivers/egl/SCsub
- drivers/gl_context/SCsub
- drivers/gles3/rasterizer_gles3.cpp
- drivers/metal/README.md
- drivers/metal/metal_objects.h
- drivers/metal/pixel_formats.h
- drivers/metal/pixel_formats.mm
- drivers/metal/rendering_device_driver_metal.mm
- drivers/png/SCsub
- drivers/png/image_loader_png.cpp
- drivers/pulseaudio/audio_driver_pulseaudio.cpp
- drivers/unix/os_unix.cpp
- drivers/vulkan/SCsub
- drivers/vulkan/rendering_device_driver_vulkan.cpp
> Deref Godot: drivers/

- .github/workflows/release.yml
Adding release runner, to get builds out
> Create release.yml for release builds

- README.md
> Fix readme typo "Keatram" to "Kaetram".

- CONTRIBUTING.md
(cherry picked from commit e747f9a2449c138cabd486e137d13e893950110c)
> [4.3] Updated CONTRIBUTING.md w/ PR Guideline and Redot Docs links

- LOGO_LICENSE.txt
> [4.3] Update LOGO_LICENSE.txt to Brandkit Provided

- platform/windows/detect.py
The log file is created with utf-8 encoding, but re-open with other encoding.
This open operation will cause build failure.
> Fix solution build failure when using Visual Studio IDE

- methods.py
> Fix build versioning to account for status_version

- scene/gui/color_mode.cpp
- scene/gui/color_mode.h
> [4.3] Unify `ColorPicker` color mode slider colors

- scene/gui/color_picker.cpp
> [4.3] Unify `ColorPicker` HSV Rectangle/Wheel draw

- scene/gui/color_mode.cpp
- scene/gui/color_mode.h
> [4.3] Fix RGB/RAW `ColorMode` jank sliders and spinbox

- scene/gui/scroll_bar.cpp
(cherry picked from commit blazium-engine/blazium@ca09c1d606e876d527ef0d67a40dbf94860050a7)
> [4.3] Fix `ScrollBar` grabber mouse ignores scroll margin

- editor/doc_tools.cpp
- editor/editor_help.cpp
- editor/editor_node.cpp
- editor/editor_property_name_processor.cpp
- editor/fbx_importer_manager.cpp
- platform/linuxbsd/wayland/display_server_wayland.cpp
Requires https://forum.redotengine.org/, https://redotengine.org/community, and https://redotengine.org/donate to exist.
> [4.3] Fix remainder of godotengine references

- editor/doc_tools.cpp
- editor/editor_help.cpp
- editor/editor_node.cpp
- editor/editor_property_name_processor.cpp
- editor/fbx_importer_manager.cpp
- platform/linuxbsd/wayland/display_server_wayland.cpp
(cherry picked from commit 1d62a70c5bb74dfbffffe1c018a861719e93e7ae)
Requires https://forum.redotengine.org/, https://redotengine.org/community, and https://redotengine.org/donate to exist.
> Fix remainder of godotengine references

- scene/main/node.cpp
(cherry picked from commit blazium-engine/blazium@474bfd82dc585948b957380cea4c0d328d8ac375)
This needs a lot of testing.
> Optimize `Node.find_children`

- misc/dist/linux/org.redotengine.Redot.appdata.xml
> [4.3] Change Godot Linux appdata urls to Redot

- editor/export/export_template_manager.cpp
Supports Redot-Engine/redot-landing-page#191
> [4.3] Add support for redotengine.org template mirror automation

- doc/classes/HTTPRequest.xml
- editor/plugins/plugin_config_dialog.cpp
- modules/gltf/editor/editor_scene_exporter_gltf_settings.cpp
- platform/web/api/web_tools_editor_plugin.cpp
> [4.3] Rebrand Godette to Redot-chan

- platform/web/api/web_tools_editor_plugin.cpp
From https://github.com/Redot-Engine/redot-engine/pull/858/files#diff-5e46215715a97b501cb8d01714c4b2e22ebc7fd5f561b0e7852b66e9f5d0c5a1R76 (forgot to rename this part of code documentation)
> [4.3] Rebrand godette into redot-chan on platformer 2 comment for consistency

- core/io/resource_loader.cpp
See godotengine/godot#99469
Related PR: #863
This reverts commit a0c17446add3a35f4b402e7c855301e5bf36cf47.
> [4.3] Revert "ResourceLoader: Report error if resource type unrecognized"

- README.md
sends you to some random guy otherwise
> Fix Twitter link in readme

- editor/editor_node.cpp
> Add donation button back

- SConstruct
- core/input/input.cpp
- core/input/input.h
- core/os/spin_lock.h
- core/os/thread.h
- core/string/ustring.cpp
- doc/classes/Input.xml
- drivers/wasapi/audio_driver_wasapi.cpp
- drivers/wasapi/audio_driver_wasapi.h
- editor/plugins/animation_player_editor_plugin.cpp
- editor/plugins/packed_scene_translation_parser_plugin.cpp
- modules/gdscript/gdscript_byte_codegen.cpp
- modules/gdscript/tests/scripts/runtime/errors/division_by_zero.gd
- modules/gdscript/tests/scripts/runtime/errors/division_by_zero.out
- modules/gdscript/tests/scripts/runtime/errors/modulo_by_zero.gd
- modules/gdscript/tests/scripts/runtime/errors/modulo_by_zero.out
- platform/windows/joypad_windows.cpp
- platform/windows/joypad_windows.h
- scene/gui/graph_edit.cpp
- scene/gui/tab_bar.cpp
- tests/core/string/test_string.h
Crash PRs:
- godotengine/godot#95172
- godotengine/godot#95795
- godotengine/godot#96309
- godotengine/godot#97032
- godotengine/godot#97288
- godotengine/godot#98357
- godotengine/godot#98792
- godotengine/godot#99168
- godotengine/godot#101541
Extra PRs:
- godotengine/godot#98861
- godotengine/godot#85167
> [4.3] Cherry-picks for the 4.3 (4.3.1) branch - 1st crashes batch

- .github/workflows/web_builds.yml
- SConstruct
- drivers/wasapi/audio_driver_wasapi.cpp
- methods.py
- modules/camera/config.py
- modules/openxr/SCsub
- platform/linuxbsd/wayland/wayland_thread.cpp
- platform/web/SCsub
- platform/web/emscripten_helpers.py
- platform/web/export/export_plugin.cpp
- platform/web/js/engine/config.js
- platform/windows/crash_handler_windows_signal.cpp
- platform/windows/detect.py
- thirdparty/linuxbsd_headers/alsa/asoundlib.h
- thirdparty/linuxbsd_headers/alsa/patches/freebsd_endian.diff
Buildsystem Bug PRs:
- godotengine/godot#97458
- godotengine/godot#97813
- godotengine/godot#98901
- godotengine/godot#98965
- godotengine/godot#99036
- godotengine/godot#99044
- godotengine/godot#100047
- godotengine/godot#100207
- godotengine/godot#100270
> [4.3] Cherry-picks for the 4.3 (4.3.1) branch - 1st buildsystem bugs batch

- drivers/coreaudio/audio_driver_coreaudio.cpp
- drivers/wasapi/audio_driver_wasapi.cpp
- editor/import/resource_importer_wav.cpp
- modules/interactive_music/audio_stream_interactive.cpp
- platform/web/js/libs/library_godot_audio.js
- scene/resources/audio_stream_wav.cpp
- scene/resources/audio_stream_wav.h
- servers/audio/effects/audio_effect_pitch_shift.cpp
- servers/audio_server.cpp
- servers/audio_server.h
Audio Bug PRs:
- godotengine/godot#97109
- godotengine/godot#97711
- godotengine/godot#98131
- godotengine/godot#98305
- godotengine/godot#98717
- godotengine/godot#100116
- godotengine/godot#100422
- godotengine/godot#100552
Extra PRs:
- godotengine/godot#95463
- godotengine/godot#96017
> [4.3] Cherry-picks for the 4.3 (4.3.1) branch - 1st audio bugs batch

- modules/gdscript/gdscript_editor.cpp
- modules/gdscript/gdscript_parser.cpp
- modules/gdscript/gdscript_parser.h
- modules/gdscript/tests/scripts/completion/assignment_options/enum_attribute.cfg
- modules/gdscript/tests/scripts/completion/assignment_options/enum_attribute.gd
- modules/gdscript/tests/scripts/completion/assignment_options/enum_attribute_identifier.cfg
- modules/gdscript/tests/scripts/completion/assignment_options/enum_attribute_identifier.gd
- modules/gdscript/tests/scripts/completion/assignment_options/enum_identifier.cfg
- modules/gdscript/tests/scripts/completion/assignment_options/enum_identifier.gd
- modules/gdscript/tests/scripts/completion/assignment_options/enum_no_identifier.cfg
- modules/gdscript/tests/scripts/completion/assignment_options/enum_no_identifier.gd
- modules/gdscript/tests/scripts/completion/index/array_type.cfg
- modules/gdscript/tests/scripts/completion/index/array_type.gd
- modules/gdscript/tests/scripts/completion/index/array_value.cfg
- modules/gdscript/tests/scripts/completion/index/array_value.gd
- modules/gdscript/tests/scripts/completion/index/const_dictionary_keys.cfg
- modules/gdscript/tests/scripts/completion/index/const_dictionary_keys.gd
- modules/gdscript/tests/scripts/completion/index/dictionary_type.cfg
- modules/gdscript/tests/scripts/completion/index/dictionary_type.gd
- modules/gdscript/tests/scripts/completion/index/dictionary_value.cfg
- modules/gdscript/tests/scripts/completion/index/dictionary_value.gd
- modules/gdscript/tests/scripts/completion/index/local_dictionary_keys.cfg
- modules/gdscript/tests/scripts/completion/index/local_dictionary_keys.gd
- modules/gdscript/tests/scripts/completion/index/property_dictionary_keys.cfg
- modules/gdscript/tests/scripts/completion/index/property_dictionary_keys.gd
- modules/gdscript/tests/scripts/completion/index/untyped_local.cfg
- modules/gdscript/tests/scripts/completion/index/untyped_local.gd
- modules/gdscript/tests/scripts/completion/index/untyped_property.cfg
- modules/gdscript/tests/scripts/completion/index/untyped_property.gd
- Fixes #953
GDScript Bug PRs:
- godotengine/godot#96693
- godotengine/godot#96326
- godotengine/godot#96243
- godotengine/godot#79378
- godotengine/godot#96160
> [4.3] Cherry-picks for the 4.3 (4.3.1) branch - 2nd gdscript bugs batch

- README.md
Update rex description and associated link
> Update README.md's rex section to reflect changes to rex

- .github/workflows/changelog_builder.yml
- Original PR: #1065 
(cherry picked from commit f8c662c71278ab90a6dc4eccbc2d8ce8753df42c)
> [4.3] Fix changelog builder tag resolver and title transformers

- .github/workflows/changelog_builder.yml
- Original PR: #1068 
(cherry picked from commit 5d834149f0e20609413c66be85c72b6a7805aa47)
> [4.3] Add user reference to PR template in changelog builder

- core/extension/gdextension_library_loader.cpp
- Original PR: #1072 
(cherry picked from commit 265c6fd3f29f17ffcfd59ae2b4862d21090f7dbe)
---
Add disable flag via `disable_godot_checks`
> [4.4] Add Godot drop-in replacement for GDExtension version checks

- platform/macos/SCsub
- Original PR: #1076
(cherry picked from commit 3fa1a3e0f8be38e2ed3ab72ddc1e7e5bc9dc6dbe)
---
May still require more fixes for iOS ~and visionOS~
> [4.3] Fix erroneous macOS build bundle generation

- editor/animation_track_editor.cpp
(cherry picked from commit 19f342e04374c3991db1dd3659feb9b4c2544abe)
Fixes issue #1064
> [4.4] Cherry Pick: Fix animation track inserted path and key type
